version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    environment:
      - FLASK_APP=src.api.app
      - FLASK_ENV=production
    restart: unless-stopped 